version: '3.8'

services:
  app:
    image: golang:1.26-alpine
    container_name: firefly-importer
    working_dir: /app
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    env_file:
      - .env
    restart: unless-stopped
    command: go run cmd/firefly-importer/main.go
    volumes:
      - .:/app
